
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Velveteen_development
  host: localhost
  port: 5432
  
test:
  <<: *default
  database: Velveteen_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: Velveteen_production
  username: Velveteen
  password: <%= ENV['VELVETEEN_DATABASE_PASSWORD'] %>
