# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
venues = Venue.create([
	{ title: "Weddings", bio: "We have performed at hundreds of upscale weddings.  A string ensemble in the configuration of your choice is our best-selling option for your ceremony, cocktail hour, dinner, and first dance. We also offer an entire string orchestra for the ultimate musical experience.  Each of our musicians is classically trained from top international music programs, and are experts in all genres.  Our in-house arranger ensures that the music performed on your big day will knock everyone's socks off! We will guide you through the process of choosing repertoire and offer suggestions along the way to help you create the perfect once-in-a-lifetime experience.", name: "https://s3.amazonaws.com/velveteenensemble/wine2.jpg"},
	{title: "Concerts & Tours", bio: "
Velveteen Ensemble has had the privilege of touring globally, collaborating with top artists, and providing award-winning performances for weddings and private events.  Most recently, we completed a 20-concert tour throughout China featuring classical, pop, and folk pieces.  We have also collaborated with hip-hop artists such as Migos and A-Boogie Wit Da Hoodie.  Ensemble members have personally toured with renowned artists such as John Legend, Sarah Bareilles, and Madonna.", name: "https://s3.amazonaws.com/velveteenensemble/PM9A1098.jpg"},
	{title: "Corporate Events", bio: "Velveteen Ensemble regularly works with Fortune 500 companies including Google, Disney, and Swarovski to provide elegant musicianship for their events.  Our musicians have played for musical segments and starred in HBO's hit tv series Game of Thrones, Amazon Prime's Mozart in the Jungle, and NBC's Law and Order, to name just a few.  We love working with all companies, big and small, to bring their productions and events to the next level.", name: "https://s3.amazonaws.com/velveteenensemble/header3.jpg"},
	{title: "Recordings", bio: "Velveteen Ensemble regularly works with talented composers looking for professional recordings of their works.  These composers include students looking to build up their portfolio to songwriters looking to incorporate strings into their albums. Please contact us if you are looking to have strings in your next project!", name: "https://s3.amazonaws.com/velveteenensemble/wine3.jpg"}
])
about = About.create([{bio: "The Velveteen Ensemble will work with you to make your event a smashing success.  Our exclusive arranger and gifted musicians will ensure that the music played, performed, or recorded is of the utmost quality.  We have years of experience performing at the most acclaimed concert halls internationally, and have just returned from a five-week, twenty-concert series in China.  We also work with top Pop and Hip Hop artists such as Migos, luxury brands such as Swarovski for their event showcases, and television networks such as HBO and Sony. We have also produced music for hit TV shows, and have significant experience performing at hundreds of luxury weddings throughout New York City for high-end clientele and celebrities.  We also perform at more private and smaller functions, such as concerts tailored to any genre and music combination imaginable.  We regularly work and record music of contemporary composers globally.  Our ensemble is here to make unforgettable experiences for our clients."}, {bio: "Our ensemble is based in New York City and its members have received graduate degrees from the most prestigious Conservatories and are experts in performing and recording Classical, Pop and Jazz Genres. Our repertoire includes classical, Bollywood, Jewish, Broadway and Pop, though we can perform virtually any piece of any genre.  We cannot wait to be a part of your next event!"}])

musicians = Musician.create([ {fname: "Marcel", lname: "Krasner", name: "https://s3.amazonaws.com/velveteenensemble/marcel.png", instrument: "Chello", bio: "lorem ipsum"}, 
	{fname: "Johnny", lname: "Appleseed", name: "https://s3.amazonaws.com/velveteenensemble/violin.png", instrument: "Violin", bio: "lorem ipsum"}, 
	{fname: "Alejandro", lname: "Leston", name: "https://s3.amazonaws.com/velveteenensemble/piano.png", instrument: "Piano", bio: "lorem ipsum"}, 
	{fname: "Pippy", lname: "Longstocking", name: "https://s3.amazonaws.com/velveteenensemble/trombone.png", instrument: "Trombone", bio: "lorem ipsum"}, 
	{fname: "Che", lname: "Guevara", name: "https://s3.amazonaws.com/velveteenensemble/flute.png", instrument: "Flute", bio: "lorem ipsum"}, 
	{fname: "Barack", lname: "Obama", name: "https://s3.amazonaws.com/velveteenensemble/drums.png", instrument: "Drums", bio: "lorem ipsum"}
])

